name: 错误报告（中文）
description: 反馈关于 MediaPipe4U 使用过程中遇到的问题
title: "[Bug]:"
assignees:
  - endink
body:
  - type: markdown
    attributes:
      value: |
         感谢你报告关于 MediaPipe4U 的问题，请认真填写这个表单，帮助我节约时间，每个人的时间都是有限的!
  - type: input
    id: m4uver
    attributes:
      label: MediaPipe4U 版本
      placeholder: 你使用哪个版本的 MediaPipe4U (例如:20230311).
    validations:
      required: true
  - type: dropdown
    id: ueversion
    attributes:
      label: UnrealEngine 版本
      description: 你使用哪个版本的虚幻引擎
      options:
        - 5.0.x
        - 5.1.x
    validations:
      required: true
  - type: dropdown
    id: uetype
    attributes:
      label: UnrealEngine 类型
      description: 你的虚幻引擎类型，对于某些问题，非常重要
      options:
        - Launcher
        - 源码编译
    validations:
      required: true
  - type: dropdown
    id: category
    attributes:
      label: 问题类型
      description: 让我知道你遇到的问题是关于哪个方面
      options:
        - 运行错误
        - 插件安装
        - 项目打包
        - 二次开发
        - 其他
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: 错误详细描述
      description: 如果可能，请上传日志文件，截图等信息，拖放这些文件到输入框即可上传，便于我复现这个错误
      placeholder: 告诉我发生了什么
    validations:
      required: true