# source "https://gems.ruby-china.com" # gems.ruby-china.com rubygems.org

# gem "jekyll-rtd-theme"

# gem "github-pages", group: :jekyll_plugins
source "https://rubygems.org"

gem "github-pages", group: :jekyll_plugins
gem "jekyll-include-cache", group: :jekyll_plugins
